routes/web.php
<?php

// Backend Page

Route::group(['prefix' => 'dev'], function () {
	
	// Dashboard
	Route::get('/', 'HomeController@dev')->name('dev');
	// Load Item To Dashboard
	Route::get('/load-items-dashboard', 'HomeController@loadItemDashboard');


	// Auth
	Route::post('/custom/login', 'AuthController@login')->name('custom.login');
	// End Auth
	

	// Users
	Route::resource('users', 'UserController');

	// Profile
	Route::get('user/profile/{id}', 'UserController@profile')->name('user.profile');

	// Change Profile
	Route::put('/user/profile/changeProfile/{id}', 'UserController@changeProfile')->name('user.changeProfile');

	// Change Password
	Route::get('user/profile/change-password/{id}', 'UserController@changePassword')->name('user.change-password');
	Route::put('user/profile/change-password/password-change/{id}', 'UserController@passwordChange')->name('user.password-change');

	// Delete Photo Profile
	Route::put('/user/profile/deletePhotoProfile/{id}', 'UserController@deletePhotoProfile')->name('user.deletePhotoProfile');

	// Danger Zone
	// Delete Account
	Route::delete('user/delete/{id}', 'UserController@deleteAccount')->name('user.delete-account');
	// End Users

	// Items
	// Trashed Zone
	// Get All Item
	Route::get('items/trashed', 'ItemController@itemsTrashed')->name('items.trashed');
	// Restore Trashed Item
	Route::get('item/restore/{id}', 'ItemController@restore')->name('item.restore');
	// Delete Permanent Item
	Route::delete('item/delete-permanent/{id}', 'ItemController@deletePermanent')->name('item.delete-permanent');
	// End Trash Zone
	Route::resource('items', 'ItemController');
	// END Items

	//Trashed zone
	Route::get('categories/trashed', 'CategoryController@categoriesTrash')->name('categories.trashed');
	// Restore Trashed Item
	Route::get('category/restore/{id}', 'CategoryController@restore')->name('category.restore');
	// Delete Permanent Item
	Route::delete('category/delete-permanent/{id}', 'CategoryController@deletePermanent')->name('category.delete-permanent');
	// Category
	// get all category with search
	Route::get('categories/get-all', 'CategoryController@getCategories')->name('categories.get-all');

	Route::resource('categories', 'CategoryController');

	// Orders 

		// Order Index
		Route::get('/orders', 'OrderController@index')->name('orders.index');
		// Create New Order
		Route::get('/order/{id}/create-new-order', 'OrderController@create')->name('order.create');
		// Make Order
		Route::post('/order', 'OrderController@store')->name('order.store');
		// Show Order
		Route::get('/order/{id}/detail-order', 'OrderController@show')->name('order.show');
		// Edit ORder
		Route::get('/order/{id}/edit-order', 'OrderController@edit')->name('order.edit');
		// Update Order
		Route::put('/order/{id}/update-order', 'OrderController@update')->name('order.update');
		// Delete Order
		Route::delete('/order/{id}', 'OrderController@destroy')->name('order.destroy');
		// Trashed Zone
		Route::get('/orders/trashed', 'OrderController@ordersTrashed')->name('orders.index.trashed');
		// Restore Data
		Route::get('/order/{id}/restore-order', 'OrderController@restore')->name('order.restore');
		// Delete Permanent Data
		Route::delete('/order/{id}/delete-permanent', 'OrderController@deletePermanent')->name('order.delete-permanent');
	// End Orders
	
});

// End Backend

// Front End
Route::group(['prefix' => 'web'], function (){
    Route::get('/', 'PageController@index')->name('home');
});
// END Front End


Route::get('/', function () {
	return view('welcome');
});

Route::get('/', 'PageController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::match(['POST', 'GET'], '/register', function () {
	return redirect('/');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // Relation to Order, Has Many
    public function user_create_orders()
    {
        return $this->hasMany('App\Order', 'order_by');
    }

    // Relation to order, Has Many
    public function user_response_order()
    {
        return $this->hasMany('App\Order', 'responded_by');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/layouts/global.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mini Mart @yield('title')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  {{-- Csrf Token --}}
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.min.css') }}">
  {{-- Style AdminLTE --}}
  <link rel="stylesheet" href="{{ asset('dist/css/skins/skin-blue.min.css') }}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{{ asset('plugins/iCheck/all.css') }}">
  <!-- Google Font -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  {{-- Pace Style --}}
  <link rel="stylesheet" href="{{ asset('plugins/pace/pace-theme-flash.css') }}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{{ asset('bower_components/select2/dist/css/select2.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.min.css') }}">
</head>

<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <!-- Main Header -->
    <header class="main-header">

      <!-- Logo -->
      <a href="{{ url('/dev') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>MM</b></span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Mini</b> Mart</span>
      </a>

      <!-- Header Navbar -->
      <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <!-- User Account Menu -->
            <li class="dropdown user user-menu">
              <!-- Menu Toggle Button -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <!-- The user image in the navbar-->
                <img src="{{ asset('images/users_images/' . Auth::user()->image) }}" class="user-image"
                  alt="User Image">
                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                <span class="hidden-xs">{{ Auth::user()->name }}</span>
              </a>
              <ul class="dropdown-menu">
                <!-- The user image in the menu -->
                <li class="user-header">
                  <img src="{{ asset('images/users_images/' . Auth::user()->image) }}" class="img-circle"
                    alt="User Image">
                  <p>
                    {{ Auth::user()->name }} - {{ Auth::user()->level }}
                  </p>
                </li>
                <!-- Menu Footer-->
                <li class="user-footer">
                  <div class="pull-left">
                    <a href="{{ route('user.profile', Auth::user()->id) }}" class="btn btn-default btn-flat">Profile</a>
                  </div>
                  <div class="pull-right">
                    <a href="{{ route('logout') }}"
                      onclick="event.preventDefault(); document.getElementById('logout-form').submit()"
                      class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

      <!-- sidebar: style can be found in sidebar.less -->
      <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
          <div class="pull-left image">
            <img src="{{ asset('images/users_images/' . Auth::user()->image) }}" class="img-circle" alt="User Image">
          </div>
          <div class="pull-left info">
            <p>{{ Auth::user()->name }}</p>
            <!-- Status -->
            <i class="fa fa-circle text-success"></i> {{ Auth::user()->level }}
          </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
          <li class="header">Menu</li>
          <li><a href="{{ url('/dev') }}"><i class="fa fa-home"></i> <span>Dashboard</span></a></li>
          
            <li class="treeview">
              <a href="#"><i class="fa fa-gear"></i> <span>Master</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{ route('users.index') }}"><i class="fa fa-users"></i> <span>Users</span></a></li>
                <li><a href="{{ route('items.index') }}"><i class="fa fa-dropbox"></i> <span>Items</span></a></li>
                <li><a href="{{ route('categories.index') }}"><i class="fa fa-circle"></i> <span>Category</span></a></li>
                <li><a href="{{ route('orders.index') }}"><i class="fa fa-shopping-cart"></i> <span>Orders</span></a></li>
              </ul>
            </li>

          <li class="treeview">
              <a href="#"><i class="fa fa-circle-o"></i> <span>Treeview</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
               
                <li><a href="#"><i class="fa fa-book"></i> <span>Menu 1</span></a></li>
              </ul>
            </li>

          <li><a href="{{ route('logout') }}"
              onclick="event.preventDefault(); document.getElementById('logout-form').submit()"><i
                class="fa fa-sign-out"></i> <span>Sign Out</span></a></li>
          <form action="{{ route('logout') }}" id="logout-form" method="POST" style="display: none;">
            @csrf
          </form>
          <!-- /.sidebar-menu -->
        </ul>
      </section>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          @yield('page-header')
          <small>@yield('page-header-optional')</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="@yield('breadcumb-link')"><i class="fa fa-dashboard"></i>@yield('breadcumb-level')</a></li>
          <li class="active">@yield('breadcumb-here')</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content container-fluid">
        
        {{-- Message Session --}}
        @include('layouts.inc.messages')

        @yield('content')

      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
        Minimarket
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2019 <a href="#">Minimart Euy</a>.</strong>
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED JS SCRIPTS -->

  <!-- jQuery 3 -->
  <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
  <!-- Bootstrap 3.3.7 -->
  <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <!-- AdminLTE App -->
  <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
  <!-- DataTables -->
  <script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
  {{-- Pace Js --}}
  <script src="{{ asset('plugins/pace/pace.min.js') }}"></script>
  {{-- Init Pace --}}
  <script>
    $(document).ajaxStart(function() {
     Pace.restart();
   });
  </script>
  <!-- Select2 -->
  <script src="{{ asset('bower_components/select2/dist/js/select2.full.min.js') }}"></script>
  <!-- ChartJS -->
  <script src="{{ asset('bower_components/chart.js/Chart.js') }}"></script>
  <!-- iCheck 1.0.1 -->
  <script src="{{ asset('plugins/iCheck/icheck.min.js') }}"></script>
  @stack('script')
</body>

</html>

resources/views/pages/categories/soft_deletes/index.blade.php
@extends('layouts.global')

@section('title', '- Trashed Category Management')

@section('page-header', 'Trashed Category Management')

@section('page-header-optional', 'Manage Your Trashed Category Here')

@section('breadcumb-link')
	{{ route('categories.trashed') }}
	@section('breadcumb-level')
		Trashed Category
	@endsection
@endsection

@section('breadcumb-here', 'Dashboard')

@section('content')
	<div class="box box-solid box-danger">
		<div class="box-header">
			<div class="box-title">
				<div class="pull-left">
				Trashed Category List
				</div>
			</div>

			<div class="pull-right">
				<a href="{{ route('categories.index') }}" class="btn btn-success"><span class="fa fa-check"> </span> Untrashed Category</a>
			</div>
		</div>

		<div class="box-body">
			<div class="pull-right">
			</div>

			<div class="table table-responsive">
				<table class="table table-striped" id="datatable">
					<thead>
						<tr>
                            <th>#</th>
							<th>Name</th>
							<th>Code</th>
						</tr>
					</thead>

					<tbody>
						@php $no = 1 @endphp
						@foreach ($categories as $category)
							<tr>
								<td>{{ $no }}.</td>
								<td>{{ $category->name }}</td>
								<td>{{ $category->code }}</td>
									{{-- Restore --}}
									<a href="{{ route('category.restore', $category->id) }}" class="btn btn-success btn-sm pull-left" style="margin-left: 10px" onclick="return confirm('Restore {{ $category->name }}')">
										<span class="fa fa-check"></span>
									</a>

									{{-- Delete Permanent --}}
									<form action="{{ route('category.delete-permanent', $category->id) }}" method="POST" onsubmit="return confirm('Delete Permanent {{ $category->name }} ? ')" class="pull-left" style="margin-left: 10px">
										@csrf
										<input type="hidden" name="_method" value="DELETE">
										<button type="submit" class="btn btn-danger btn-sm">
											<span class="fa fa-trash"></span>
										</button>
									</form>
								</td>
							</tr>
						@php $no++ @endphp
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection

@push('script')
	<script>
		$(function (){
			$('#datatable').DataTable();
		});
	</script>
@endpush

resources/views/pages/items/create.blade.php
@extends('layouts.global')

@section('title', '- Item Management')

@section('page-header', 'Item Management')

@section('page-header-optional', 'Create New Item')

@section('breadcumb-link')
	{{ route('items.index') }}
	@section('breadcumb-level')
		Items
	@endsection
@endsection

@section('breadcumb-here', 'Create')

@section('content')
	<div class="box box-solid box-primary">
		<div class="box-header">
			<div class="box-title">
				<div class="pull-left">
					Create New Item
				</div>
			</div>

			<div class="pull-right">
				<a href="{{ route('items.index') }}" class="btn btn-danger"> Go Back</a>
			</div>
		</div>

		<div class="box-body">
			<form action="{{ route('items.store') }}" method="POST" onsubmit="return confirm('Create New Item ? ')" enctype="multipart/form-data">
				@csrf
			<div class="row">
				<div class="col-md-6">
					<div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
						<label for="name">Name</label>
						<input type="text" name="name" id="name" class="form-control" placeholder="Name" autocomplete="off" value="{{ old('name') }}">

						<div class="help-block">
							{{ $errors->first('name') }}
						</div>
					</div>

					<div class="form-group {{ $errors->first('') ? 'has-error' : '' }}">
						<label for="categories">Attach Categories For Item</label>
						<select name="categories[]" id="categories" class="form-control" style="width:100%" multiple>

						</select>
					</div>

					<div class="form-group {{ $errors->first('desc') ? 'has-error' : '' }}">
						<label for="desc">Description</label>

                        <textarea name="desc" id="desc" value="{{ old('desc') }}" class="form-control" cols="30" rows="10">
                            {{ old('desc') }}
                        </textarea>

						<div class="help-block">
							{{ $errors->first('desc') }}
						</div>
					</div>

					<div class="form-group {{ $errors->first('stock') ? 'has-error' : '' }}">
						<label for="stock">Stock</label>
						<input type="number" name="stock" id="stock" class="form-control" placeholder="Stock" autocomplete="off" value="{{ old('stock') }}">

						<div class="help-block">
							{{ $errors->first('stock') }}
						</div>
                    </div>

					<div class="form-group {{ $errors->first('price') ? 'has-error' : '' }}">
						<label for="price">price</label>
						<input type="number" name="price" id="price" class="form-control" value="{{ old('price') }}" placeholder="Price">

						<div class="help-block">
							{{ $errors->first('price') }}
						</div>
					</div>

				</div>

                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" name="image" id="image">
                </div>
			</div>
		</div>
        <div class="box-footer">
            <button type="submit" name="submit" class="btn btn-primary pull-right">
                Create User
            </button>
        </div>
			</form>
@endsection


@push('script')
<script>
    // Via ServerSide
    $(function() {
        $('#categories').select2({
			placeholder: 'Choose Categories',
			ajax : {
				url : '{{ route("categories.get-all") }}',
				processResults : function(data){
					return {
						results : data.map(function(category){
							return {id:category.id, text:category.name}
						})
					}
				}
			}
		});
    });
</script>
@endpush

resources/views/pages/items/edit.blade.php
@extends('layouts.global')

@section('title')
	- Update {{ $item->name }}
@endsection

@section('page-header', 'Update Item')

@section('page-header-optional')
	Update {{ $item->name }}
@endsection

@section('breadcumb-link')
	{{ route('items.index') }}
	@section('breadcumb-level')
		Users
	@endsection
@endsection

@section('breadcumb-here', 'Update')
	
@section('content')
	<div class="box box-solid box-primary">
		<div class="box-header">
			<div class="box-title">
				<div class="pull-left">
					Update {{ $item->name }}
				</div>
			</div>

			<div class="pull-right">
				<a href="{{ route('items.index') }}" class="btn btn-danger"> Go Back</a>
			</div>
		</div>

		<div class="box-body">
            <form action="{{ route('items.update', $item->id) }}" method="POST" onsubmit="return confirm('Update {{ $item->name }} ? ')" enctype="multipart/form-data">
                
				@csrf
                <input type="hidden" name="_method" value="PUT">
                
			<div class="row">
				<div class="col-md-6">
					<div class="form-group {{ $errors->first('name') ? 'has-error' : '' }}">
						<label for="name">Name</label>
						<input type="text" name="name" id="name" class="form-control" placeholder="Name" autocomplete="off" value="{{ $item->name }}">

						<div class="help-block">
							{{ $errors->first('name') }}
						</div>
					</div>

					<div class="form-group {{ $errors->first('') ? 'has-error' : '' }}">
						<label for="categories">Attach Categories For Item</label>
						<select name="categories[]" id="categories" class="form-control" style="width:100%" multiple>
							
						</select>
					</div>
					
					<div class="form-group {{ $errors->first('desc') ? 'has-error' : '' }}">
						<label for="desc">Desc</label>
						<input type="desc" name="desc" id="desc" class="form-control" placeholder="desc" autocomplete="off" value="{{ $item->desc }}">

						<div class="help-block">
							{{ $errors->first('desc') }}
						</div>
					</div>

					<div class="form-group {{ $errors->first('stock') ? 'has-error' : '' }}">
						<label for="stock">Stock</label>
						<input type="number" name="stock" id="stock" class="form-control" value="{{ $item->stock }}">
						<div class="help-block">
							{{ $errors->first('stock') }}
						</div>
					</div>

					<div class="form-group {{ $errors->first('price') ? 'has-error' : '' }}">
						<label for="price">Price</label>
						<input type="number" name="price" id="price" class="form-control" value="{{ $item->price }}">

						<div class="help-block">
							{{ $errors->first('price') }}
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<label for="image">Image</label>
						<input type="file" name="image" id="image">

						<img src="{{ asset('images/items_images/' .$item->image) }}" width="100" style="margin-top: 10px;" alt="" srcset="">
					</div>
				</div>
			</div>
		</div>

		<div class="box-footer">
			<button type="submit" name="submit" class="btn btn-primary pull-right">
				Update Item
			</button>
		</div>
			</form>				
	</div>	
@endsection

@push('script')
	<script>
		$(function() {
			$('#categories').select2({
				placeholder: 'Choose Categories',
				ajax : {
					url : '{{ route("categories.get-all") }}',
					processResults : function(data){
						return {
							results : data.map(function(category){
								return {id:category.id, text:category.name}
							})
						}
					}
				}
			});

			var categories = {!! $item->category_item !!}
            categories.forEach(function(category){
                var option = new Option(category.name, category.id, true, true);
                $('#categories').append(option).trigger('change');
            });
		})
	</script>
@endpush

resources/views/pages/items/index.blade.php
@extends('layouts.global')

@section('title', '- Item Management')

@section('page-header', 'Item Management')

@section('page-header-optional', 'Manage Your Items Here')

@section('breadcumb-link')
	{{ route('items.index') }}
	@section('breadcumb-level')
		Users
	@endsection
@endsection

@section('breadcumb-here', 'Dashboard')

@section('content')
	<div class="box box-solid box-primary">
		<div class="box-header">
			<div class="box-title">
				<div class="pull-left">
				Item List
				</div>
			</div>

			<div class="pull-right">
				<a href="{{ route('items.create') }}" class="btn btn-success"><span class="fa fa-plus"> </span> Create New Items</a>
				<a href="{{ route('items.trashed') }}" class="btn btn-danger"><span class="fa fa-trash"></span>Trashed Items</a>
			</div>
		</div>

		<div class="box-body">
			<div class="pull-right">
			</div>

			<div class="table table-responsive">
				<table class="table table-striped" id="datatable">
					<thead>
						<tr>
                            <th>#</th>
							<th>Image</th>
							<th>Name</th>
							<th>Code</th>
							<th>Stock</th>
							<th>Price</th>
							<th> Action </th>
						</tr>
					</thead>

					<tbody>
						@php $no = 1 @endphp
						@foreach ($items as $item)
							<tr>
								<td>{{ $no }}.</td>
								<td>
									<img src="{{ asset('images/items_images/' . $item->image) }}" alt="images" srcset="" width="48px">
								</td>
								<td>{{ $item->name }}</td>
								<td>{{ $item->code }}</td>
								<td>{{ $item->stock }}</td>
								<td>Rp. {{ number_format($item->price) }}</td>
								<td>
									<a href="{{ route('items.show', $item->id) }}" class="btn btn-primary btn-sm pull-left" style="margin-left: 10px">
										<span class="fa fa-eye"></span>
									</a>
									<a href="{{ route('items.edit', $item->id) }}" class="btn btn-warning btn-sm pull-left" style="margin-left: 10px">
										<span class="fa fa-edit"></span>
									</a>
									<form action="{{ route('items.destroy', $item->id) }}" method="POST" onsubmit="return confirm('Delete {{ $item->name }} ? ')" class="pull-left" style="margin-left: 10px">
										@csrf
										<input type="hidden" name="_method" value="DELETE">
										<button type="submit" class="btn btn-danger btn-sm">
											<span class="fa fa-trash"></span>
										</button>
									</form>
								</td>
							</tr>
						@php $no++ @endphp
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
@endsection

@push('script')
	<script>
		$(function (){
			$('#datatable').DataTable();
		});
	</script>
@endpush

resources/views/pages/users/index.blade.php
@extends('layouts.global')

@section('title', '- User Management')

@section('page-header', 'User Management')

@section('page-header-optional', 'Manage Your Users Here')

@section('breadcumb-link')
	{{ route('users.index') }}
	@section('breadcumb-level')
		Users
	@endsection
@endsection

@section('breadcumb-here', 'Dashboard')

@section('content')
	<div class="box box-solid box-primary">
		<div class="box-header">
			<div class="box-title">
				<div class="pull-left">
				 	User List
				</div>
			</div>

			<div class="pull-right">
				<a href="{{ route('users.create') }}" class="btn btn-success"><span class="fa fa-plus"></span> Create New User</a>
			</div>
		</div>

		<div class="box-body">
			<div class="pull-right">
			</div>

			<div class="table table-responsive">
				<table class="table table-striped" id="datatable">
					<thead>
						<tr>
							<th>#</th>
							<th>Image</th>
							<th>Name</th>
							<th>Username</th>
							<th>Email</th>
							<th>Level</th>
							<th>Status</th>
							<th></th>
						</tr>
					</thead>

					<tbody>
						@php $no = 1 @endphp
						@foreach($users as $user)
							<tr>
								<td>{{ $no++ }}</td>
								<td>
									<img src="{{ asset('images/users_images/' . $user->image) }}" width="48px">
								</td>
								<td>{{ $user->name }}</td>
								<td>{{ $user->username }}</td>
								<td>{{ $user->email }}</td>
								<td>
									<div class="{{ $user->level == 'ADMIN' ? 'label label-success' : '' }}">
										{{ $user->level }}
									</div>
								</td>
								<td>{{ $user->status }}</td>
								<td>
									<a href="{{ route('users.show', $user->id) }}" class="btn btn-primary btn-sm pull-left" style="margin-left: 10px">
										<span class="fa fa-eye"></span>
									</a>
									<a href="{{ route('users.edit', $user->id) }}" class="btn btn-warning btn-sm pull-left" style="margin-left: 10px">
										<span class="fa fa-edit"></span>
									</a>
									<form action="{{ route('users.destroy', $user->id) }}" method="POST" onsubmit="return confirm('Delete {{ $user->name }} ? ')" class="pull-left" style="margin-left: 10px">
										@csrf
										<input type="hidden" name="_method" value="DELETE">
										<button type="submit" class="btn btn-danger btn-sm">
											<span class="fa fa-trash"></span>
										</button>
									</form>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
			{{-- Pagination --}}
			<div class="box-footer pull-right">
				{{ $users->appends(Request::all())->links() }}
			</div>
		</div>
	</div>
@endsection

@push('script')
	<script>
		$(function() {
			$('#datatable').DataTable()
		})
	</script>
@endpush